services:
  docs:
    image: cookiecutter_playground_local_docs
    container_name: cookiecutter_playground_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./cookiecutter_playground:/app/cookiecutter_playground:z
    ports:
      - '9000:9000'
    command: /start-docs
