volumes:
  cookiecutter_playground_local_postgres_data: {}
  cookiecutter_playground_local_postgres_data_backups: {}
  cookiecutter_playground_local_redis_data: {}
  cookiecutter_playground_local_rabbitmq_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: cookiecutter_playground_local_django
    container_name: cookiecutter_playground_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '4000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cookiecutter_playground_production_postgres
    container_name: cookiecutter_playground_local_postgres
    volumes:
      - cookiecutter_playground_local_postgres_data:/var/lib/postgresql/data
      - cookiecutter_playground_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - '5431:5432'

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: cookiecutter_playground_local_mailpit
    ports:
      - "4025:8025"

  redis:
    image: docker.io/redis:6
    container_name: cookiecutter_playground_local_redis
    volumes:
      - cookiecutter_playground_local_redis_data:/data
    ports:
      - "6378:6379"

  rabbitmq:
    image: rabbitmq:management
    container_name: cookiecutter_playground_local_rabbitmq
    volumes:
      - cookiecutter_playground_local_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  celeryworker:
    <<: *django
    image: cookiecutter_playground_local_celeryworker
    container_name: cookiecutter_playground_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celeryworker_email:
    <<: *django
    image: cookiecutter_playground_local_celeryworker
    container_name: cookiecutter_playground_local_celeryworker_email
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker-email

  celeryworker_database:
    <<: *django
    image: cookiecutter_playground_local_celeryworker
    container_name: cookiecutter_playground_local_celeryworker_database
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker-database

  celerybeat:
    <<: *django
    image: cookiecutter_playground_local_celerybeat
    container_name: cookiecutter_playground_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: cookiecutter_playground_local_flower
    container_name: cookiecutter_playground_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
